config/routes.rb
Alpaga::Application.routes.draw do
  resources :categories 
  
  get 'catalogue' => "categories#collection"

  get "login" => "static_pages#login"
  get "contact.vcf" => "static_pages#contact_vcf"

  resources :colors

  root :to => 'articles#home'

  resources :media
  resources :produits
  resources :articles
  resources :users

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/signout' => 'sessions#destroy', :as => :signout

  match '/edito/:short_url' => 'articles#short_url'
  match '/page/:large_page' => 'articles#large_page'

  match '/collection' => "produits#collection"
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :corps, :titre, :url, :medium_id
  belongs_to :medium
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_admin
  skip_before_filter :require_admin, :only=> [:show, :short_url, :home, :large_page]

  # GET /edito/foo
  def large_page
    name = params[:large_page] || "home"
    @article = Article.where(:url => name).first 
    if @article.nil? 
      @article = Article.new
      @article.url = name;
      @article.save
    end
    render "large"
  end

  # GET /edito/foo
  def short_url
    name = params[:short_url] || "home"
    @article = Article.where(:url => name).first 
    if @article.nil? 
      @article = Article.new
      @article.url = name;
      @article.save
    end
    render "show"
  end

  # GET /
  def home
    name = "home"
    @article = Article.where(:url => name).first 
    if @article.nil? 
      @article = Article.new
      @article.url = name;
      @article.save
    end
    render "show"
  end

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
.edito
  = simple_form_for @article, html: {class: 'form-inline'} do |f|
    = f.input :titre
    = f.input :url, :label => "Nom court"
    = f.input :corps, :input_html => { :data => {:provide => "markdown"}}
    %br
    = f.association :medium, :collection => Medium.where("id not in (select medium_id from articles where id != ? and medium_id not null)", @article.id), as: :radio_buttons, label_method: :vignette
    %br
    = f.button :submit

app/views/articles/edit.html.haml
%h1 Modifictaion d'un article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/home.html.haml
#leftcolumn.span11
#rightcolumn.span1
  .home_edito
    %h2
      = @article.titre
    = markdown(@article.corps)


  - if admin?
    = link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_article_path(@article), :class => "btn"
    = link_to '<i class="icon-th-list"></i>Back'.html_safe, articles_path, :class => "btn"

app/views/articles/index.html.haml
%h1 Listing articles

%table.table
  %tr
    %th
    %th Titre
    %th Url
    %th Corps
    %th
    %th
    %th

  - @articles.each do |article|
    %tr
      %td
        - if article.medium
          = image_tag article.medium.file.url(:thumb)
      %td= article.titre
      %td= article.url
      %td= article.corps
      %td= link_to '<i class="icon-file"></i> Show'.html_safe, article, :class => "btn"
      %td= link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_article_path(article), :class => "btn"
      %td= link_to '<i class="icon-trash"></i> Destroy'.html_safe, article, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn"

%br

= link_to 'New Article', new_article_path, :class => "btn btn-primary"

app/views/articles/large.html.haml
.span6
.span6
  .rightcolumn
    - if @article.medium
      %script
        function init_bg() {
        $('body').css('background','url("#{@article.medium.file.url()}") no-repeat center center fixed');
        $('body').css('background-size','cover');
        }
    %h2
      = @article.titre
    = markdown(@article.corps)


  - if admin?
    = link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_article_path(@article), :class => "btn"
    = link_to '<i class="icon-th-list"></i>Back'.html_safe, articles_path, :class => "btn"

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
#leftcolumn.span11
#rightcolumn.span1
  .rightcolumn
    - if @article.medium
      %script
        function init_bg() {
        $('body').css('background','url("#{@article.medium.file.url()}") no-repeat center center fixed');
        $('body').css('background-size','cover');
        }
    %h2
      = @article.titre
    = markdown(@article.corps)


  - if admin?
    = link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_article_path(@article), :class => "btn"
    = link_to '<i class="icon-th-list"></i>Back'.html_safe, articles_path, :class => "btn"