config/routes.rb
Alpaga::Application.routes.draw do
  resources :categories 
  
  get 'catalogue' => "categories#collection"

  get "login" => "static_pages#login"
  get "contact.vcf" => "static_pages#contact_vcf"

  resources :colors

  root :to => 'articles#home'

  resources :media
  resources :produits
  resources :articles
  resources :users

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/signout' => 'sessions#destroy', :as => :signout

  match '/edito/:short_url' => 'articles#short_url'
  match '/page/:large_page' => 'articles#large_page'

  match '/collection' => "produits#collection"
end

app/models/produit.rb
class Produit < ActiveRecord::Base
  attr_accessible :description, :ref, :medium_ids, :color_ids, :promo_id, :status, :category_id, :tri
  has_many :medium, :order => :tri
  accepts_nested_attributes_for :medium, :allow_destroy => true
  has_and_belongs_to_many :colors
  belongs_to :promo, :class_name => 'Medium'
  belongs_to :category

  extend FriendlyId
  friendly_id :ref, use: :slugged

  def premiere_photo 
    if medium.first
      medium.first
    else
      Medium.all.first
    end
  end

  def photo_promo
    promo || premiere_photo
  end

  def colors_with_photo
    colors.select { |color| color.photo }
  end

  def toutes_les_photos
    photos = Array.new
    photos.concat(medium)
    photos.concat(colors_with_photo.map {|c| c.photo})
  end
end

app/controllers/produits_controller.rb
class ProduitsController < ApplicationController
  before_filter :require_admin
  skip_before_filter :require_admin, :only=> [:show, :collection]

  # GET /produits
  # GET /produits.json
  def index
    @produits = Produit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produits }
    end
  end

  # GET /collection
  def collection
    @produits = Produit.where(:status => true).order(:tri)
    @nb_lignes = (@produits.size / 6.0).ceil
    @nb_produits = (@produits.size / (@nb_lignes + 0.0)).ceil  
    if (@nb_lignes == 1) 
      @marge = 10 
    else   
      @marge = 2 
    end
    render "collection"
  end

  # GET /produits/1
  # GET /produits/1.json
  def show
    @produit = Produit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produit }
    end
  end

  # GET /produits/new
  # GET /produits/new.json
  def new
    @produit = Produit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produit }
    end
  end

  # GET /produits/1/edit
  def edit
    @produit = Produit.find(params[:id])
  end

  # POST /produits
  # POST /produits.json
  def create
    @produit = Produit.new(params[:produit])

    respond_to do |format|
      if @produit.save
        format.html { redirect_to @produit, notice: 'Produit was successfully created.' }
        format.json { render json: @produit, status: :created, location: @produit }
      else
        format.html { render action: "new" }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /produits/1
  # PUT /produits/1.json
  def update
    @produit = Produit.find(params[:id])

    respond_to do |format|
      if @produit.update_attributes(params[:produit])
        format.html { redirect_to @produit, notice: 'Produit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produits/1
  # DELETE /produits/1.json
  def destroy
    @produit = Produit.find(params[:id])
    @produit.destroy

    respond_to do |format|
      format.html { redirect_to produits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/produits_helper.rb
module ProduitsHelper
end

app/views/produits/_form.html.haml
.edito
  = simple_form_for @produit, html: {class: 'form-inline'} do |f|
    = f.input :ref, :label => "Référence"
    = f.input :description
    = f.input :status, :label => "Publié"
    = f.input :tri, :label => "Ordre"
    %h3 Photos
    = f.association :medium, :collection => Medium.where('id not in (select medium_id from colors where medium_id not null) and (produit_id is null or produit_id = ?) ',@produit.id), as: :check_boxes, label_method: :vignette, :label => "Photos"
    = f.association :colors, as: :check_boxes, label_method: :vignette, :label => "Couleurs"
    = f.association :promo, :collection => Medium.list_potential_promo(@produit.id), as: :radio_buttons, label_method: :vignette
    = f.association :category, :collection => Category.all
    = f.button :submit

app/views/produits/collection.html.haml
.span12.hidden-phone.text-center
  %div{ style:"margin-top:#{@marge}%"}
    - @produits.each_slice(@nb_produits) do |lot_produits|
      .liste_produits_pc
        %table.ligne_produits_pc
          %tr
            - lot_produits.each do |produit|
              %td.text-center= link_to image_tag(produit.photo_promo.file.url(:medium), :class => "produit_dans_la_liste"), produit
- @produits.each do |produit|
  .hidden-desktop.hidden-tablet.span2.text-center= link_to image_tag(produit.photo_promo.file.url(:medium), :class => "produit_mobile"), produit

app/views/produits/edit.html.haml
%h1 Édition d'un produit

= render 'form'

= link_to 'Show', @produit
\|
= link_to 'Back', produits_path

app/views/produits/index.html.haml
%h1 Liste des produits

%table.table
  %tr
    %th
    %th Ref
    %th Description
    %th
    %th
    %th

  - @produits.each do |produit|
    %tr
      %td= produit.status
      %td= image_tag produit.premiere_photo.file.url(:thumb)
      %td= produit.ref
      %td= produit.description
      %td= link_to '<i class="icon-file"></i> Show'.html_safe, produit, :class => "btn"
      %td= link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_produit_path(produit), :class => "btn"
      %td= link_to '<i class="icon-trash"></i> Destroy'.html_safe, produit, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn"

%br

= link_to 'Nouveau produit', new_produit_path, :class => "btn btn-primary"

app/views/produits/new.html.haml
%h1 New produit

= render 'form'

= link_to 'Back', produits_path

app/views/produits/show.html.haml
#leftcolumn.span11
#rightcolumn.span1
  .rightcolumn
    %script
      function init_bg() {
      $('body').css('background','url(#{@produit.premiere_photo.file.url()}) no-repeat center center fixed');
      $('body').css('background-size','cover');
      }

    %p.visible-phone
      #mobil-carousel-switch.visible-phone.text-center
        - num = 0
        - @produit.medium.each do |photo|
          %a.popup-link{href:photo.url(:medium)}
            %img{:src => "#{photo.url(:thumb)}", :class=>"photo", :id=>"p#{photo.id}"}

          - num = num +1
    %p
      %h3= @produit.ref
      = markdown(@produit.description)
    %p.hidden-phone
      #pc-carousel-switch.hidden-phone
        - num = 0
        - @produit.medium.each do |vignette|
          %img{:src => "#{vignette.url(:thumb)}", :class=>"photo", :id=>"p#{vignette.id}", :data =>{:target => "#fond", :slide => {:to => "#{num}"}}}
          - num = num +1

    %p
      %br
      Couleurs disponibles :
      %br
      - color_num = num
      .text-center
        #mobil-couleur-switch.visible-phone
          - @produit.colors.each do |color|
            %figure.vignette_couleur
              - if color.photo
                %a.popup-link{href:color.url(:medium)}
                  %img{:src => "#{color.url(:thumb)}", :class=>"couleur", :id=>"c#{color.id}"}
                - num = num +1
              - else
                %img{:src => "#{color.url(:thumb)}", :class=>"couleur", :id=>"c#{color.id}"}
              %figcaption  
                =color.name
      #pc-couleur-switch.hidden-phone
        - num = color_num
        - @produit.colors.each do |color|
          %figure.vignette_couleur
            - if color.photo
              %img{:src => "#{color.url(:thumb)}", :class=>"couleur", :id=>"c#{color.id}", :data =>{:target => "#fond", :slide => {:to => "#{num}"}}}
              - num = num +1
            - else
              %img{:src => "#{color.url(:thumb)}", :class=>"couleur", :id=>"c#{color.id}"}
            %figcaption  
              =color.name
    %p
      %a{href:"/page/entretien"} Conseils d'entretien

    .pull-right= social_share_button_tag(@produit.ref)

    #fond.carousel.hidden-phone.slide{:data => {:interval => "false"}}
      .carousel-inner
        - num = 0
        - @produit.toutes_les_photos.each do |photo|
          - num = num +1
          - if (num==1)
            .item.active
              =image_tag photo.file.url()
          - else 
            .item
              =image_tag photo.file.url()

  - if admin?
    = link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_produit_path(@produit), :class => "btn"
    = link_to '<i class="icon-th-list"></i>Back'.html_safe, produits_path, :class => "btn"