config/routes.rb
Alpaga::Application.routes.draw do
  resources :categories 
  
  get 'catalogue' => "categories#collection"

  get "login" => "static_pages#login"
  get "contact.vcf" => "static_pages#contact_vcf"

  resources :colors

  root :to => 'articles#home'

  resources :media
  resources :produits
  resources :articles
  resources :users

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/signout' => 'sessions#destroy', :as => :signout

  match '/edito/:short_url' => 'articles#short_url'
  match '/page/:large_page' => 'articles#large_page'

  match '/collection' => "produits#collection"
end

app/models/color.rb
class Color < ActiveRecord::Base
  attr_accessible :name, :medium_id, :photo_id
  belongs_to :medium
  belongs_to :photo, :class_name => 'Medium'

  def vignette
    medium.vignette
  end

  def url(size=:thumb)
    medium.url(size)
  end
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  # GET /colors
  # GET /colors.json
  def index
    @colors = Color.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @colors }
    end
  end

  # GET /colors/1
  # GET /colors/1.json
  def show
    @color = Color.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @color }
    end
  end

  # GET /colors/new
  # GET /colors/new.json
  def new
    @color = Color.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @color }
    end
  end

  # GET /colors/1/edit
  def edit
    @color = Color.find(params[:id])
  end

  # POST /colors
  # POST /colors.json
  def create
    @color = Color.new(params[:color])

    respond_to do |format|
      if @color.save
        format.html { redirect_to @color, notice: 'Color was successfully created.' }
        format.json { render json: @color, status: :created, location: @color }
      else
        format.html { render action: "new" }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /colors/1
  # PUT /colors/1.json
  def update
    @color = Color.find(params[:id])

    respond_to do |format|
      if @color.update_attributes(params[:color])
        format.html { redirect_to @color, notice: 'Color was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1
  # DELETE /colors/1.json
  def destroy
    @color = Color.find(params[:id])
    @color.destroy

    respond_to do |format|
      format.html { redirect_to colors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/views/colors/_form.html.haml
.edito
  = simple_form_for @color, html: {class: 'form-inline'} do |f|
    = f.input :name
    = f.association :medium, :collection => Medium.list_potential_color(@color.id), as: :radio_buttons, label_method: :vignette
    = f.association :photo, :collection => Medium.list_potential_color(@color.id), as: :radio_buttons, label_method: :vignette
    = f.button :submit

app/views/colors/edit.html.haml
%h1 Editing color

= render 'form'

= link_to 'Show', @color
\|
= link_to 'Back', colors_path

app/views/colors/index.html.haml
%h1 Liste des couleurs

= link_to 'Nouvelle couleur', new_color_path, :class => "btn btn-primary"

%table.table
  %tr
    %th
    %th Nom
    %th
    %th
    %th

  - @colors.each do |color|
    %tr
      %td
        - if color.medium
          = image_tag color.medium.file.url(:thumb)
      %td= color.name
      %td= link_to '<i class="icon-file"></i> Show'.html_safe, color, :class => "btn"
      %td= link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_color_path(color), :class => "btn"
      %td= link_to '<i class="icon-trash"></i> Destroy'.html_safe, color, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn"

%br

= link_to 'Nouvelle couleur', new_color_path, :class => "btn btn-primary"

app/views/colors/new.html.haml
%h1 New color

= render 'form'

= link_to 'Back', colors_path

app/views/colors/show.html.haml
.span2
.span8
  .edito
    - if @color.photo
      %script
        function init_bg() {
        $('body').css('background','url("#{@color.photo.file.url()}") no-repeat center center fixed');
        $('body').css('background-size','cover');
        }

    %h2= @color.name
    - if @color.medium
      %br
      = image_tag @color.medium.file.url(:thumb)

  - if admin?
    = link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_color_path(@color), :class => "btn"
    = link_to '<i class="icon-th-list"></i>Back'.html_safe, colors_path, :class => "btn"